## Whats is Churn?

Churn rate, in its broadest sense, is a measure of the number of individuals or items moving out of a collective group over a specific period. It is one of two primary factors that determine the steady-state level of customers a business will support, According to Wikipedia

This competition is about predicting whether a customer will change telecommunications provider, something known as "churning".

The training dataset contains 4250 samples. Each sample contains 19 features and 1 boolean variable "churn" which indicates the class of the sample. The 19 input features and 1 target variable are:

"state", string. 2-letter code of the US state of customer residence

"account_length", numerical. Number of months the customer has been with the current telco provider

"area_code", string="area_code_AAA" where AAA = 3 digit area code.

"international_plan", (yes/no). The customer has international plan.


"voice_mail_plan", (yes/no). The customer has voice mail plan.

"number_vmail_messages", numerical. Number of voice-mail messages.

"total_day_minutes", numerical. Total minutes of day calls.

"total_day_calls", numerical. Total minutes of day calls.
"total_day_charge", numerical. Total charge of day calls.

"total_eve_minutes", numerical. Total minutes of evening calls.

"total_eve_calls", numerical. Total number of evening calls.

"total_eve_charge", numerical. Total charge of evening calls.

"total_night_minutes", numerical. Total minutes of night calls.

"total_night_calls", numerical. Total number of night calls.

"total_night_charge", numerical. Total charge of night calls.

"total_intl_minutes", numerical. Total minutes of international calls.

"total_intl_calls", numerical. Total number of international calls.


"total_intl_charge", numerical. Total charge of international calls

"number_customer_service_calls", numerical. Number of calls to customer service

"churn", (yes/no). Customer churn - target variable.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv('customer_churn/train.csv')

In [3]:
data

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
0,OH,107,area_code_415,no,yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,no
1,NJ,137,area_code_415,no,no,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,no
2,OH,84,area_code_408,yes,no,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,no
3,OK,75,area_code_415,yes,no,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,no
4,MA,121,area_code_510,no,yes,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,MT,83,area_code_415,no,no,0,188.3,70,32.01,243.8,88,20.72,213.7,79,9.62,10.3,6,2.78,0,no
4246,WV,73,area_code_408,no,no,0,177.9,89,30.24,131.2,82,11.15,186.2,89,8.38,11.5,6,3.11,3,no
4247,NC,75,area_code_408,no,no,0,170.7,101,29.02,193.1,126,16.41,129.1,104,5.81,6.9,7,1.86,1,no
4248,HI,50,area_code_408,no,yes,40,235.7,127,40.07,223.0,126,18.96,297.5,116,13.39,9.9,5,2.67,2,no
4249,VT,86,area_code_415,no,yes,34,129.4,102,22.00,267.1,104,22.70,154.8,100,6.97,9.3,16,2.51,0,no

In [4]:
#Checking for Datatypes
data.dtypes

state                             object
account_length                     int64
area_code                         object
international_plan                object
voice_mail_plan                   object
number_vmail_messages              int64
total_day_minutes                float64
total_day_calls                    int64
total_day_charge                 float64
total_eve_minutes                float64
total_eve_calls                    int64
total_eve_charge                 float64
total_night_minutes              float64
total_night_calls                  int64
total_night_charge               float64
total_intl_minutes               float64
total_intl_calls                   int64
total_intl_charge                float64
number_customer_service_calls      int64
churn                             object
dtype: object

In [5]:
data.groupby('state').count()

,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
state,,,,,,,,,,,,,,,,,,,
AK,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61
AL,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101
AR,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71
AZ,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77
CA,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39
CO,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80
CT,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88
DC,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72
DE,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80
FL,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76
GA,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
HI,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77
IA,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62
ID,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106
IL,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79
IN,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83
KS,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87
KY,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85
LA,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69
MA,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89
MD,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86
ME,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89,89
MI,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87
MN,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108,108
MO,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80
MS,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82
MT,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80
NC,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80
ND,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67
NE,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73
NH,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78
NJ,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96
NM,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78
NV,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83
NY,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96
OH,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95
OK,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78
OR,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
PA,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67
RI,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87
SC,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72
SD,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75
TN,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79
TX,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98
UT,97,97,97,97,97,97,97,97,97,97,97,97,97,97,97,97,97,97,97
VA,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100
VT,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86
WA,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80
WI,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94,94
WV,139,139,139,139,139,139,139,139,139,139,139,139,139,139,139,139,139,139,139
WY,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95,95

In [6]:
data.groupby('state').mean()

,account_length,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls
state,,,,,,,,,,,,,,,
AK,99.245902,9.409836,178.427869,98.606557,30.333279,188.209836,98.557377,15.997541,197.934426,99.016393,8.906885,10.109836,4.901639,2.730328,1.344262
AL,95.188119,7.643564,189.318812,100.029703,32.184356,199.546535,98.217822,16.961683,189.314851,97.405941,8.519406,10.453465,4.485149,2.822673,1.603960
AR,94.816901,10.014085,169.452113,97.676056,28.807324,192.081690,99.450704,16.327324,203.125352,102.788732,9.141127,10.194366,4.605634,2.752676,1.816901
AZ,103.324675,9.688312,176.911688,98.259740,30.075714,196.548052,101.415584,16.706753,188.428571,100.051948,8.479870,10.676623,4.714286,2.883247,1.519481
CA,99.589744,5.871795,171.082051,102.512821,29.084615,190.874359,103.076923,16.225128,200.423077,95.205128,9.019231,9.671795,4.615385,2.612051,1.307692
CO,98.225000,7.887500,173.491250,97.650000,29.494250,208.077500,99.712500,17.686375,191.708750,96.300000,8.627500,9.866250,4.100000,2.664250,1.800000
CT,96.829545,9.295455,180.560227,98.159091,30.695568,201.845455,98.375000,17.157045,201.737500,102.136364,9.078523,10.360227,4.056818,2.797500,1.579545
DC,105.708333,10.569444,170.616667,101.541667,29.005833,196.195833,101.347222,16.677361,210.216667,103.041667,9.459861,10.225000,3.902778,2.761389,1.388889
DE,97.675000,7.850000,182.797500,99.962500,31.076125,207.815000,96.087500,17.664750,205.265000,98.825000,9.237125,10.546250,4.225000,2.849000,1.737500
FL,114.052632,8.223684,173.413158,101.197368,29.480658,214.081579,108.026316,18.197368,202.135526,100.460526,9.096053,10.069737,4.210526,2.719211,1.605263
GA,100.015625,8.156250,178.448438,102.921875,30.336562,205.642188,104.937500,17.479688,200.018750,102.812500,9.000937,10.537500,4.281250,2.845937,1.750000
HI,102.792208,6.714286,181.735065,103.025974,30.894935,196.542857,98.948052,16.705584,203.520779,101.532468,9.158312,10.415584,4.961039,2.812727,1.558442
IA,94.193548,6.661290,175.883871,101.806452,29.901452,205.109677,98.403226,17.434677,196.232258,99.645161,8.831129,9.551613,4.225806,2.579355,1.564516
ID,98.886792,7.632075,183.475472,103.566038,31.191415,193.459434,102.028302,16.444434,201.540566,101.028302,9.069528,10.616038,4.735849,2.866792,1.660377
IL,98.113924,7.405063,175.503797,98.696203,29.836076,193.179747,100.215190,16.420633,197.101266,94.189873,8.869620,10.049367,3.962025,2.713924,1.227848
IN,98.144578,8.132530,188.319277,106.156627,32.014940,205.278313,98.566265,17.448675,206.409639,100.349398,9.288313,9.909639,4.120482,2.675783,1.734940
KS,104.528736,8.367816,191.083908,100.022989,32.484483,208.549425,102.183908,17.726667,202.220690,101.275862,9.100460,10.747126,4.436782,2.902069,1.517241
KY,97.682353,7.352941,180.491765,99.458824,30.684941,193.214118,98.164706,16.423294,201.468235,102.870588,9.066235,10.824706,4.176471,2.923059,1.517647
LA,99.463768,8.260870,171.608696,104.347826,29.174203,202.682609,97.130435,17.228696,191.447826,100.492754,8.615362,9.673913,4.521739,2.613043,1.550725
MA,93.943820,8.224719,184.585393,98.528090,31.379663,205.506742,99.044944,17.468652,203.053933,95.415730,9.137865,9.753933,4.471910,2.634382,1.348315
MD,99.976744,6.383721,190.667442,98.290698,32.414302,191.416279,97.290698,16.270698,203.559302,98.953488,9.160000,10.527907,4.383721,2.843023,1.639535
ME,95.471910,7.337079,184.961798,98.337079,31.444270,201.703371,104.011236,17.145056,201.507865,101.561798,9.067753,10.014607,4.539326,2.704719,1.786517
MI,100.666667,8.436782,171.870115,99.333333,29.218506,200.245977,100.931034,17.021149,194.894253,100.954023,8.770230,10.710345,4.758621,2.891839,1.689655
MN,101.935185,6.990741,181.196296,101.574074,30.804074,196.513889,100.361111,16.703889,207.035185,101.277778,9.316389,10.154630,4.222222,2.742315,1.564815
MO,100.350000,6.312500,173.125000,100.200000,29.432375,201.532500,99.362500,17.130375,211.418750,99.637500,9.513875,9.857500,5.037500,2.662000,1.700000
MS,105.317073,8.256098,172.975610,98.975610,29.406341,200.410976,101.597561,17.035366,204.529268,100.573171,9.203537,10.540244,4.060976,2.846463,1.634146
MT,96.175000,8.325000,174.077500,96.750000,29.593125,203.283750,94.312500,17.279250,197.010000,100.375000,8.865250,10.708750,4.537500,2.891750,1.637500
NC,99.912500,8.312500,177.703750,100.062500,30.210125,198.681250,103.112500,16.888500,197.413750,100.537500,8.883625,10.063750,4.475000,2.717750,1.362500
ND,102.731343,7.731343,182.573134,100.402985,31.038358,208.664179,105.805970,17.736418,197.305970,103.313433,8.878657,10.425373,4.626866,2.815522,1.358209
NE,104.191781,6.273973,175.397260,97.904110,29.817945,203.584932,103.191781,17.304521,198.657534,98.972603,8.940000,10.410959,4.164384,2.811644,1.424658
NH,104.217949,7.589744,178.241026,99.641026,30.301923,196.384615,99.141026,16.693077,205.634615,95.128205,9.253718,10.384615,4.384615,2.804744,1.589744
NJ,101.927083,6.802083,192.972917,100.843750,32.805729,193.603125,100.854167,16.456458,202.498958,101.270833,9.112813,10.705208,4.614583,2.891146,1.583333
NM,100.512821,5.294872,175.252564,100.217949,29.792949,205.887179,102.423077,17.500385,199.501282,99.884615,8.977179,10.488462,4.692308,2.833077,1.500000
NV,97.879518,7.734940,181.763855,99.686747,30.900361,204.280723,98.385542,17.363976,203.567470,101.168675,9.160241,10.120482,4.265060,2.732410,1.686747
NY,100.354167,5.468750,176.995833,97.270833,30.089792,195.554167,102.645833,16.622396,203.705208,98.447917,9.167292,9.909375,4.593750,2.675521,1.656250
OH,99.800000,10.305263,188.112632,99.842105,31.979684,198.186316,102.378947,16.846105,206.363158,101.947368,9.286526,10.260000,4.210526,2.770632,1.473684
OK,101.064103,6.628205,191.917949,98.948718,32.626282,196.876923,103.076923,16.735641,200.365385,98.205128,9.015897,10.470513,4.525641,2.828205,1.769231
OR,99.454545,6.656566,177.946465,95.595960,30.251717,201.932323,97.323232,17.164646,200.100000,104.969697,9.004747,10.501010,4.333333,2.835859,1.727273
PA,105.298507,7.402985,186.719403,97.776119,31.742687,194.998507,102.149254,16.574627,203.167164,98.462687,9.143284,10.243284,3.910448,2.765522,1.328358
RI,102.080460,6.528736,177.871264,98.425287,30.238851,207.404598,97.367816,17.629770,206.903448,97.758621,9.310805,10.111494,4.494253,2.730690,1.425287
SC,97.194444,8.416667,171.109722,102.027778,29.089722,206.508333,98.819444,17.552778,196.031944,101.444444,8.821806,9.772222,4.263889,2.639306,1.583333
SD,105.386667,9.386667,185.190667,97.226667,31.482800,201.686667,98.600000,17.143333,202.890667,96.400000,9.130533,10.073333,4.666667,2.720267,1.560000
TN,101.848101,7.455696,179.026582,100.189873,30.435063,207.036709,102.316456,17.598481,203.610127,95.721519,9.162785,10.370886,4.493671,2.800506,1.455696
TX,99.489796,6.306122,185.676531,100.632653,31.565306,200.792857,101.173469,17.067245,196.138776,101.948980,8.826224,10.231633,4.000000,2.762755,1.673469
UT,101.185567,8.680412,188.469072,98.948454,32.040309,196.993814,98.474227,16.744948,193.463918,98.474227,8.705464,9.965979,4.567010,2.691031,1.309278
VA,103.450000,6.240000,177.009000,100.850000,30.092000,199.382000,100.120000,16.948000,204.503000,95.900000,9.203000,10.442000,4.690000,2.819800,1.440000
VT,105.290698,7.511628,179.518605,101.546512,30.519070,208.744186,96.813953,17.743837,206.156977,100.674419,9.276977,10.103488,4.837209,2.728372,1.686047
WA,100.150000,5.462500,180.011250,101.337500,30.602375,201.518750,96.337500,17.129750,196.061250,101.875000,8.823000,9.748750,4.650000,2.632875,1.512500
WI,100.287234,7.925532,175.931915,98.893617,29.908511,194.368085,100.808511,16.521809,193.069149,98.882979,8.688511,9.819149,4.010638,2.651596,1.287234
WV,94.676259,7.316547,177.564029,100.705036,30.186619,190.447482,99.733813,16.187626,199.686331,99.302158,8.986115,10.438129,4.446043,2.818921,1.690647
WY,97.515789,7.494737,185.443158,100.357895,31.525684,203.329474,99.747368,17.283158,195.265263,100.778947,8.786947,10.403158,4.610526,2.809263,1.357895

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4250 entries, 0 to 4249
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   state                          4250 non-null   object
 1   account_length                 4250 non-null   int64
 2   area_code                      4250 non-null   object
 3   international_plan             4250 non-null   object
 4   voice_mail_plan                4250 non-null   object
 5   number_vmail_messages          4250 non-null   int64
 6   total_day_minutes              4250 non-null   float64
 7   total_day_calls                4250 non-null   int64
 8   total_day_charge               4250 non-null   float64
 9   total_eve_minutes              4250 non-null   float64
 10  total_eve_calls                4250 non-null   int64
 11  total_eve_charge               4250 non-null   float64
 12  total_night_minutes            4250 non-null   float64
 13  total_night_calls              4250 non-null   int64
 14  total_night_charge             4250 non-null   float64
 15  total_intl_minutes             4250 non-null   float64
 16  total_intl_calls               4250 non-null   int64
 17  total_intl_charge              4250 non-null   float64
 18  number_customer_service_calls  4250 non-null   int64
 19  churn                          4250 non-null   object
dtypes: float64(8), int64(7), object(5)
memory usage: 664.2+ KB

In [8]:
data.isna().sum()

state                            0
account_length                   0
area_code                        0
international_plan               0
voice_mail_plan                  0
number_vmail_messages            0
total_day_minutes                0
total_day_calls                  0
total_day_charge                 0
total_eve_minutes                0
total_eve_calls                  0
total_eve_charge                 0
total_night_minutes              0
total_night_calls                0
total_night_charge               0
total_intl_minutes               0
total_intl_calls                 0
total_intl_charge                0
number_customer_service_calls    0
churn                            0
dtype: int64

In [9]:
data.iloc[0]

state                                       OH
account_length                             107
area_code                        area_code_415
international_plan                          no
voice_mail_plan                            yes
number_vmail_messages                       26
total_day_minutes                        161.6
total_day_calls                            123
total_day_charge                         27.47
total_eve_minutes                        195.5
total_eve_calls                            103
total_eve_charge                         16.62
total_night_minutes                      254.4
total_night_calls                          103
total_night_charge                       11.45
total_intl_minutes                        13.7
total_intl_calls                             3
total_intl_charge                          3.7
number_customer_service_calls                1
churn                                       no
Name: 0, dtype: object

In [10]:
data.iloc[0].value_counts('voice_mail_plan')

103              0.10
no               0.10
OH               0.05
3.7              0.05
3                0.05
13.7             0.05
11.45            0.05
254.4            0.05
16.62            0.05
195.5            0.05
107              0.05
27.47            0.05
123              0.05
161.6            0.05
26               0.05
yes              0.05
area_code_415    0.05
1                0.05
Name: 0, dtype: float64

In [11]:
data['voice_mail_plan_id'] = data['voice_mail_plan'].apply(lambda x: 0 if x == 'no' else 1)

In [12]:
data['voice_mail_plan_id'] == 1

0        True
1       False
2       False
3       False
4        True
        ...
4245    False
4246    False
4247    False
4248     True
4249     True
Name: voice_mail_plan_id, Length: 4250, dtype: bool

In [13]:
data.drop('voice_mail_plan', axis =1, inplace = True)

In [14]:
data['area_code'] = data['area_code'].str.replace('area_code_', '').astype('int')

In [15]:
data.head()

,state,account_length,area_code,international_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn,voice_mail_plan_id
0,OH,107,415,no,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,no,1
1,NJ,137,415,no,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,no,0
2,OH,84,408,yes,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,no,0
3,OK,75,415,yes,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,no,0
4,MA,121,510,no,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,no,1

In [16]:
data['area_code'].dtypes

dtype('int32')

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4250 entries, 0 to 4249
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   state                          4250 non-null   object
 1   account_length                 4250 non-null   int64
 2   area_code                      4250 non-null   int32
 3   international_plan             4250 non-null   object
 4   number_vmail_messages          4250 non-null   int64
 5   total_day_minutes              4250 non-null   float64
 6   total_day_calls                4250 non-null   int64
 7   total_day_charge               4250 non-null   float64
 8   total_eve_minutes              4250 non-null   float64
 9   total_eve_calls                4250 non-null   int64
 10  total_eve_charge               4250 non-null   float64
 11  total_night_minutes            4250 non-null   float64
 12  total_night_calls              4250 non-null   int64
 13  total_night_charge             4250 non-null   float64
 14  total_intl_minutes             4250 non-null   float64
 15  total_intl_calls               4250 non-null   int64
 16  total_intl_charge              4250 non-null   float64
 17  number_customer_service_calls  4250 non-null   int64
 18  churn                          4250 non-null   object
 19  voice_mail_plan_id             4250 non-null   int64
dtypes: float64(8), int32(1), int64(8), object(3)
memory usage: 647.6+ KB

In [18]:
data['international_plan'] = data['international_plan'].apply(lambda x: 0 if x == 'no' else 1)

In [19]:
data.head()

,state,account_length,area_code,international_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn,voice_mail_plan_id
0,OH,107,415,0,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,no,1
1,NJ,137,415,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,no,0
2,OH,84,408,1,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,no,0
3,OK,75,415,1,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,no,0
4,MA,121,510,0,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,no,1

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4250 entries, 0 to 4249
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   state                          4250 non-null   object
 1   account_length                 4250 non-null   int64
 2   area_code                      4250 non-null   int32
 3   international_plan             4250 non-null   int64
 4   number_vmail_messages          4250 non-null   int64
 5   total_day_minutes              4250 non-null   float64
 6   total_day_calls                4250 non-null   int64
 7   total_day_charge               4250 non-null   float64
 8   total_eve_minutes              4250 non-null   float64
 9   total_eve_calls                4250 non-null   int64
 10  total_eve_charge               4250 non-null   float64
 11  total_night_minutes            4250 non-null   float64
 12  total_night_calls              4250 non-null   int64
 13  total_night_charge             4250 non-null   float64
 14  total_intl_minutes             4250 non-null   float64
 15  total_intl_calls               4250 non-null   int64
 16  total_intl_charge              4250 non-null   float64
 17  number_customer_service_calls  4250 non-null   int64
 18  churn                          4250 non-null   object
 19  voice_mail_plan_id             4250 non-null   int64
dtypes: float64(8), int32(1), int64(9), object(2)
memory usage: 647.6+ KB

In [26]:
data['state'].unique()

array(['OH', 'NJ', 'OK', 'MA', 'MO', 'LA', 'WV', 'IN', 'RI', 'IA', 'MT',
       'NY', 'ID', 'VA', 'TX', 'FL', 'CO', 'AZ', 'SC', 'WY', 'HI', 'NH',
       'AK', 'GA', 'MD', 'AR', 'WI', 'OR', 'MI', 'DE', 'UT', 'CA', 'SD',
       'NC', 'WA', 'MN', 'NM', 'NV', 'DC', 'VT', 'KY', 'ME', 'MS', 'AL',
       'NE', 'KS', 'TN', 'IL', 'PA', 'CT', 'ND'], dtype=object)

In [27]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [29]:
state_encoder = data['state']

In [30]:
le.fit(state_encoder)

LabelEncoder()

In [31]:
le.classes_

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
       'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object)

In [32]:
le.transform(state_encoder)

array([35, 31, 35, ..., 27, 11, 46])

In [33]:
data['state'] = le.transform(state_encoder)

In [34]:
data.head()

,state,account_length,area_code,international_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn,voice_mail_plan_id
0,35,107,415,0,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,no,1
1,31,137,415,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,no,0
2,35,84,408,1,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,no,0
3,36,75,415,1,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,no,0
4,19,121,510,0,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,no,1

In [35]:
data.dtypes

state                              int32
account_length                     int64
area_code                          int32
international_plan                 int64
number_vmail_messages              int64
total_day_minutes                float64
total_day_calls                    int64
total_day_charge                 float64
total_eve_minutes                float64
total_eve_calls                    int64
total_eve_charge                 float64
total_night_minutes              float64
total_night_calls                  int64
total_night_charge               float64
total_intl_minutes               float64
total_intl_calls                   int64
total_intl_charge                float64
number_customer_service_calls      int64
churn                             object
voice_mail_plan_id                 int64
dtype: object

In [36]:
X = data.drop('churn', axis = 1)
y = data['churn']

In [37]:
data[data['state']==35]

,state,account_length,area_code,international_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn,voice_mail_plan_id
0,35,107,415,0,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,no,1
2,35,84,408,1,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,no,0
125,35,65,408,0,0,187.9,116,31.94,157.6,117,13.40,227.3,86,10.23,7.5,6,2.03,1,no,0
129,35,83,415,0,0,337.4,120,57.36,227.4,116,19.33,153.9,114,6.93,15.8,7,4.27,0,yes,0
190,35,63,415,1,36,199.0,110,33.83,291.3,111,24.76,197.6,92,8.89,11.0,6,2.97,1,no,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4050,35,86,408,0,26,141.3,120,24.02,134.6,98,11.44,195.9,94,8.82,13.3,5,3.59,1,no,1
4161,35,108,415,0,30,126.0,124,21.42,202.4,84,17.20,186.4,99,8.39,8.6,1,2.32,1,no,1
4171,35,111,408,1,0,145.8,106,24.79,172.5,143,14.66,143.9,123,6.48,11.9,4,3.21,1,no,0
4198,35,145,408,0,0,185.9,106,31.60,209.7,112,17.82,224.7,87,10.11,9.3,4,2.51,2,no,0
4239,35,125,415,0,0,214.7,115,36.50,260.6,94,22.15,266.3,123,11.98,7.4,6,2.00,3,no,0

In [38]:
data['churn'].unique()

array(['no', 'yes'], dtype=object)

In [39]:
data.value_counts(['churn'])

churn
no       3652
yes       598
dtype: int64

In [40]:
data.head(3)

,state,account_length,area_code,international_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn,voice_mail_plan_id
0,35,107,415,0,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,no,1
1,31,137,415,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,no,0
2,35,84,408,1,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,no,0

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
model = RandomForestClassifier(n_estimators=250)

In [44]:
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=250)

In [45]:
y_pred = model.predict(X_test)

In [46]:
y_true = y_test

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true, y_pred)

0.9647058823529412

In [48]:
from sklearn.inspection import permutation_importance

In [51]:
result = permutation_importance(model, X_train, y_train,  random_state=0)

In [52]:
more = pd.DataFrame(result.importances_mean, index= X_train.columns)*100

In [68]:
more

                                      0
state                          0.464706
account_length                 0.488235
area_code                      0.000000
international_plan             4.923529
number_vmail_messages          1.105882
total_day_minutes              4.682353
total_day_calls                0.547059
total_day_charge               3.664706
total_eve_minutes              1.258824
total_eve_calls                0.670588
total_eve_charge               1.382353
total_night_minutes            0.723529
total_night_calls              0.676471
total_night_charge             0.664706
total_intl_minutes             0.600000
total_intl_calls               2.641176
total_intl_charge              1.047059
number_customer_service_calls  5.835294
voice_mail_plan_id             0.270588

## On Testing Data Set

In [73]:
test = pd.read_csv('customer_churn/test.csv', index_col ='id')

In [74]:
test

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls
id,,,,,,,,,,,,,,,,,,,
1,KS,128,area_code_415,no,yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1
2,AL,118,area_code_510,yes,no,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0
3,IA,62,area_code_415,no,no,0,120.7,70,20.52,307.2,76,26.11,203.0,99,9.14,13.1,6,3.54,4
4,VT,93,area_code_510,no,no,0,190.7,114,32.42,218.2,111,18.55,129.6,121,5.83,8.1,3,2.19,3
5,NE,174,area_code_415,no,no,0,124.3,76,21.13,277.1,112,23.55,250.7,115,11.28,15.5,5,4.19,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,GA,130,area_code_415,no,no,0,119.4,99,20.30,226.3,97,19.24,202.7,111,9.12,11.3,7,3.05,0
747,WA,73,area_code_408,no,no,0,177.2,118,30.12,270.5,84,22.99,241.8,112,10.88,12.3,2,3.32,3
748,WV,152,area_code_415,no,no,0,184.2,90,31.31,256.8,73,21.83,213.6,113,9.61,14.7,2,3.97,3
749,DC,61,area_code_415,no,no,0,140.6,89,23.90,172.8,128,14.69,212.4,97,9.56,13.6,4,3.67,1
750,DC,109,area_code_510,no,no,0,188.8,67,32.10,171.7,92,14.59,224.4,89,10.10,8.5,6,2.30,0

In [75]:
test['voice_mail_plan_id'] = test['voice_mail_plan'].apply(lambda x: 0 if x == 'no' else 1)

In [76]:
test.head(2)

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,voice_mail_plan_id
id,,,,,,,,,,,,,,,,,,,,
1,KS,128,area_code_415,no,yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.7,1,1
2,AL,118,area_code_510,yes,no,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.7,0,0

In [77]:
test.drop('voice_mail_plan', axis =1, inplace = True)

In [78]:
test['area_code'] = test['area_code'].str.replace('area_code_', '').astype('int')

In [79]:
test['international_plan'] = test['international_plan'].apply(lambda x: 0 if x == 'no' else 1)

In [80]:
test.head(2)

,state,account_length,area_code,international_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,voice_mail_plan_id
id,,,,,,,,,,,,,,,,,,,
1,KS,128,415,0,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.7,1,1
2,AL,118,510,1,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.7,0,0

In [81]:
state_encoderT = test['state']
le.fit(state_encoderT)

LabelEncoder()

In [82]:
test

,state,account_length,area_code,international_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,voice_mail_plan_id
id,,,,,,,,,,,,,,,,,,,
1,KS,128,415,0,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,1
2,AL,118,510,1,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,0
3,IA,62,415,0,0,120.7,70,20.52,307.2,76,26.11,203.0,99,9.14,13.1,6,3.54,4,0
4,VT,93,510,0,0,190.7,114,32.42,218.2,111,18.55,129.6,121,5.83,8.1,3,2.19,3,0
5,NE,174,415,0,0,124.3,76,21.13,277.1,112,23.55,250.7,115,11.28,15.5,5,4.19,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,GA,130,415,0,0,119.4,99,20.30,226.3,97,19.24,202.7,111,9.12,11.3,7,3.05,0,0
747,WA,73,408,0,0,177.2,118,30.12,270.5,84,22.99,241.8,112,10.88,12.3,2,3.32,3,0
748,WV,152,415,0,0,184.2,90,31.31,256.8,73,21.83,213.6,113,9.61,14.7,2,3.97,3,0
749,DC,61,415,0,0,140.6,89,23.90,172.8,128,14.69,212.4,97,9.56,13.6,4,3.67,1,0
750,DC,109,510,0,0,188.8,67,32.10,171.7,92,14.59,224.4,89,10.10,8.5,6,2.30,0,0

In [83]:
test['state'] = le.transform(state_encoderT)

In [84]:
test.head(2)

,state,account_length,area_code,international_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,voice_mail_plan_id
id,,,,,,,,,,,,,,,,,,,
1,16,128,415,0,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.7,1,1
2,1,118,510,1,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.7,0,0

In [85]:
model.predict(test)

array(['no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'yes', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no',
       'yes', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no',
       'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no',
       'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no',
       'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'yes', 'no', 'no', 'no', 'yes', 'no', 'yes', 'yes', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no',
       'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no',
       'yes', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'yes', 'no', 'no',
       'yes', 'no', 'yes', 'no', 'no', 'yes', 'no', 'yes', 'no', 'no',
       'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no',
       'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'yes', 'no', 'no', 'no',
       'no', 'yes', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'yes',
       'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'no', 'yes', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'yes', 'no', 'no',
       'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'yes', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'yes', 'no', 'yes', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'yes', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no',
       'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'yes', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no',
       'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no',
       'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes',
       'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no',
       'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'yes', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no'], dtype=object)